---
- name: Create Jenkins group
  group: name={{user_name}} state=present
  tags:
    - setup

- name: Create Jenkins user
  user:
    name={{user_name}} group={{user_name}} groups={{user_groups}} comment="Jenkins User"
    home="{{jenkins_home_dir}}" state=present
  tags:
    - setup
