- name: Setup avocado repository
  get_url:
    url: http://avocado-project.org/data/repos/avocado-el.repo
    dest: /etc/yum.repos.d/avocado.repo
    force: yes
    owner: root
    group: root
    mode: 0644
  tags:
    - setup
