---
- name: Allow seed job to run without manual approval
  copy:
    src: javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration.xml
    dest: "{{jenkins_home_dir}}/javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration.xml"
  notify: restart jenkins
  tags:
    - setup

- name: Create seed job directory
  file:
    state: directory
    dest: "{{seed_job_target_dir}}"
    owner: jenkins
    group: jenkins
    mode: "0755"
  notify: restart jenkins
  tags:
    - setup

- name: Create seed job
  template:
    src: "{{seed_job_template}}"
    dest: "{{seed_job_target_dir}}/config.xml"
    owner: jenkins
    group: jenkins
    mode: "0644"
  notify: restart jenkins
  tags:
    - setup
