---
- name: Setup host for Build Verification Tests
  hosts: bvt-host
  remote_user: root
  roles:
    - selinux
    - time
    - packages-jenkins-slave
    - user
    - ssh
    - avocado-repo
    - avocado
  vars_files:
    - vars-bvt.yaml
  vars_prompt:
    - name: "jenkins_private_ssh_key_file_path"
      prompt: "Enter Jenkins private SSH key file path"
      default: "~/.ssh/jenkins_id_rsa"
      private: no
    - name: "jenkins_public_ssh_key_file_path"
      prompt: "Enter Jenkins public SSH key file path"
      default: "~/.ssh/jenkins_id_rsa.pub"
      private: no
