---
user_name: jenkins-slave
user_groups: ''
user_home_dir: "/home/{{user_name}}"
jenkins_home_dir: "{{user_home_dir}}"

avocado_dir: "{{ansible_env.HOME}}/avocado"

avocado_data_dir: "{{avocado_dir}}/data"
avocado_iso_dir: "{{avocado_dir}}/isos"
avocado_log_dir: "{{avocado_dir}}/job-results"
avocado_test_dir: "{{avocado_dir}}/tests"

avocado_conf_dir: "{{ansible_env.HOME}}/.config/avocado"
avocado_conf: "{{avocado_conf_dir}}/avocado.conf"

avocado_vt_repo: "https://github.com/open-power-host-os/avocado-vt.git"
avocado_vt_branch: "master"
avocado_vt_repo_dir: "{{ansible_env.HOME}}/bvt/avocado-vt"

test_providers_dir: "{{avocado_data_dir}}/avocado-vt/test-providers.d"
test_providers_downloads_dir: "{{test_providers_dir}}/downloads"

avocado_dirs:
  - "{{ansible_env.HOME}}"
  - "{{avocado_dir}}"
  - "{{avocado_data_dir}}"
  - "{{avocado_iso_dir}}"
  - "{{avocado_log_dir}}"
  - "{{avocado_test_dir}}"
  - "{{avocado_conf_dir}}"
  - "{{avocado_vt_repo_dir}}"
  - "{{test_providers_dir}}"
  - "{{test_providers_downloads_dir}}"

avocado_repos:
  - { repo: "https://github.com/autotest/tp-libvirt.git",
  dest: "{{test_providers_downloads_dir}}/io-github-autotest-libvirt" }
  - { repo: "https://github.com/autotest/tp-qemu.git",
  dest: "{{test_providers_downloads_dir}}/io-github-autotest-qemu" }
  - { repo: "https://github.com/spiceqa/tp-spice.git",
  dest: "{{test_providers_downloads_dir}}/io-github-spiceqa-spice" }
  - { repo: "https://github.com/open-power-host-os/bvt.git",
  dest: "{{test_providers_downloads_dir}}/host-os-bvt" }

avocado_http_ports: 8000-8004/tcp
