---
avocado_dir: "{{ansible_env.HOME}}/avocado"

avocado_data_dir: "{{avocado_dir}}/data"
avocado_iso_dir: "{{avocado_dir}}/isos"
avocado_log_dir: "{{avocado_dir}}/job-results"
avocado_test_dir: "{{avocado_dir}}/tests"

avocado_conf_dir: "{{ansible_env.HOME}}/.config/avocado"
avocado_conf: "{{avocado_conf_dir}}/avocado.conf"

test_providers_dir: "{{avocado_data_dir}}/avocado-vt/test-providers.d/downloads"

avocado_repos:
  - { repo: "https://github.com/autotest/tp-libvirt.git", dest: "{{test_providers_dir}}/io-github-autotest-libvirt" }
  - { repo: "https://github.com/autotest/tp-qemu.git", dest: "{{test_providers_dir}}/io-github-autotest-qemu" }
  - { repo: "https://github.com/spiceqa/tp-spice.git", dest: "{{test_providers_dir}}/io-github-spiceqa-spice" }

avocado_http_ports: 8000-8004/tcp
