# This is necessary to create virbr0 interface. You can create it
# manually, but libvirt does the job for you.
- name: Start libvirtd service
  service:
    name: libvirtd
    state: started
    enabled: yes
  tags:
    - setup

# Those ports are used to provide kickstart files via HTTP
- name: Open ports in firewalld
  firewalld:
    port: "{{avocado_http_ports}}"
    state: enabled
    permanent: yes
    immediate: yes
  tags:
    - setup

- name: Creating avocado directories
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{avocado_conf_dir}}"
    - "{{avocado_data_dir}}"
    - "{{avocado_iso_dir}}"
    - "{{avocado_log_dir}}"
    - "{{avocado_test_dir}}"
    - "{{avocado_vt_repo_dir}}"
    - "{{test_providers_dir}}"
    - "{{test_providers_downloads_dir}}"
  tags:
    - setup

- name: Clone avocado-vt
  git:
    repo: "{{avocado_vt_repo}}"
    version: "{{avocado_vt_branch}}"
    dest: "{{avocado_vt_repo_dir}}"
    update: yes
  notify:
    - vt-install
    - vt-bootstrap
  tags:
    - setup

- name: Setup avocado configuration
  template:
    src: avocado.conf.j2
    dest: "{{avocado_conf}}"
    owner: root
    group: root
    mode: 0644
  notify: vt-bootstrap
  tags:
    - setup

- name: Setup test providers
  copy:
    src: host-os-bvt.ini
    dest: "{{test_providers_dir}}/host-os-bvt.ini"
    owner: root
    group: root
    mode: 0644
  notify: vt-bootstrap
  tags:
    - setup

- name: Cloning test providers
  git:
    repo: "{{item.repo}}"
    dest: "{{item.dest}}"
    update: yes
  notify: vt-bootstrap
  with_items:
    - "{{avocado_repos}}"
  tags:
    - setup
